Fleet/Controllers/DocumentController.cs
using CipherLib;
using CYGNUS.Classes;
using Fleet.Classes;
using Fleet.Filters;
using Fleet.ViewModels;
using FleetDataService.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Serialization; 
using WebMatrix.WebData;

namespace Fleet.Controllers
{
    [Authorize]
    [NoDirectAccess]
    public class DocumentController : BaseController
    {
        FleetDataService.MasterService MS = new FleetDataService.MasterService();
        GeneralFuncations GF = new GeneralFuncations();
        FleetDataService.DocumentService DS = new FleetDataService.DocumentService();

        #region Scan FM Documents

        public ActionResult ScanFMDocuments()
        {
            Webx_FM_Scan_DocumentsViewModel WFSDVM = new Webx_FM_Scan_DocumentsViewModel
            {
                WFSDM = new Webx_FM_Scan_Documents(),
                ListWFSDM = new List<Webx_FM_Scan_Documents>()
            };
            return View(WFSDVM);
        }

        public ActionResult ADDFMScanInfo(int id)
        {
            Webx_FM_Scan_Documents WMFSM = new Webx_FM_Scan_Documents
            {
                Srno = id,
                ScanStatus = 1,
                Status = "Not Scanned"
            };
            return PartialView("_PartialFMScanDocument", WMFSM);
        }

        public JsonResult CheckScanFMDocno(string DocNo, string DocType, string DocumentNo)
        {
            decimal count = 0;
            var status = "";
            var DcoNo = "";
            var DocketNo = "";
            string DocumentName = "", DocumentHref = "";
            string FileMsg = "";
            byte ScanStatus = 1;
            if (DocumentNo == "" || DocumentNo == null || DocumentNo == "N/A")
            {
                DataTable Dt = DS.CheckScanFMDocno(DocNo, DocType, BaseLocationCode, HeadOfficeCode);
                if (Dt.Rows.Count > 0)
                {
                    count = 1;
                    DcoNo = Dt.Rows[0][3].ToString();
                    DocketNo = Dt.Rows[0]["DocketNo"].ToString();
                    if (DcoNo == "")
                    {
                        DcoNo = "N/A";
                    }
                    status = "Not Scanned";
                    ScanStatus = 1;
                    if (Dt.Rows[0]["DocType"].ToString() != "")
                    {
                        if (HeadOfficeCode != BaseLocationCode)
                        {
                            status = "Scanned";
                            ScanStatus = 2;
                        }
                        else
                        {
                            status = "POD Already Uploaded, you can overwrite";
                            ScanStatus = 3;
                        }
                    }
                    try
                    {
                        DocumentName = Dt.Rows[0]["DocumentName"].ToString();
                        DocumentHref = Dt.Rows[0]["DocumentHref"].ToString();
                    }
                    catch (Exception)
                    {
                        DocumentName = "";
                    }
                }
                else
                {
                    count = 0;
                    status = "Not Scanned";
                }
                return Json(new { CNT = count, Status = status, DcoNo = DcoNo, DocketNo = DocketNo, ScanStatus = ScanStatus, DocumentName = DocumentName, FileMsg = FileMsg, CurrLoc = BaseLocationCode, DocumentHref = DocumentHref }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { CNT = 1, Status = "Not Scanned", DcoNo = DocumentNo, DocketNo = DocNo, ScanStatus = ScanStatus, DocumentName = DocumentName, CurrLoc = BaseLocationCode, DocumentHref = DocumentHref }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult AddScanDoucment(List<Webx_FM_Scan_Documents> FMScan, IEnumerable<HttpPostedFileBase> files)
        {
            string DocketNo = "";//, PODFileName = "";
            var Tranxaction = "";
            var DocumentUploadedPath = "";
            try
            {
                int id = 0;
                Webx_FM_Scan_DocumentsViewModel WFSDVM = new Webx_FM_Scan_DocumentsViewModel();
                WFSDVM.ListWFSDM = FMScan;

                var now = DateTime.Now;
                var yearName = now.ToString("yyyy");
                var monthName = now.ToString("MMMM");

                foreach (var item in WFSDVM.ListWFSDM)
                {
                    //var path = "";
                    var fileName = "";
                    string newFName = "";


                    var sql = "SELECT CodeDesc FROM Webx_Master_General WHERE CodeType='FMDOC' AND StatusCode='Y' AND CodeId='" + item.DocType + "'";
                    DataTable DT = GF.getdatetablefromQuery(sql);
                    string docktypeName = DT.Rows[0][0].ToString();

                    if (files != null)
                    {
                        if (((System.Web.HttpPostedFileBase[])(files))[id] != null)
                        {
                            var file = ((System.Web.HttpPostedFileBase[])(files))[id];
                            fileName = file.FileName;
                            double dblFileSize = Convert.ToDouble(file.ContentLength) / 1000;
                            double MaxSize = 1024; //1MB

                            if (file.ContentLength > 0 && dblFileSize < MaxSize)
                            {
                                //string PATHDONO = item.DocketNo;
                                string extension = System.IO.Path.GetExtension(file.FileName);
                                newFName = GetFileName(file.FileName, item.DocketNo.Trim(), BasicUtility.GetFMDocketTypeSuffix(item.DocType.ToString()));

                                string DB_SavedPath = docktypeName + "/" + System.DateTime.Now.ToString("yyyy/MMM");

                                string FolDerPath = "D:\\SRLApplicationCode\\POD\\FMScanDocument\\" + DB_SavedPath;
                                if (!Directory.Exists(FolDerPath))
                                    Directory.CreateDirectory(FolDerPath);

                                DocumentUploadedPath = DB_SavedPath + "/" + newFName;
                                file.SaveAs(FolDerPath + "\\" + newFName);

                            }
                        }
                    }

                    id++;
                    DataTable Dt = DS.AddEditScanDocument(item.DocType, item.DocketNo, (item.DocumentNo == "N/A" ? item.DocumentNo = "" : item.DocumentNo), item.ScanStatus, fileName, DocumentUploadedPath, System.DateTime.Now, BaseUserName, BaseLocationCode);

                    DocketNo = DocketNo == "" ? Dt.Rows[0]["DocketNo"].ToString() : DocketNo + "," + Dt.Rows[0]["DocketNo"].ToString();
                    Tranxaction = "Done";
                }
            }
            catch (Exception ex)
            {
                Tranxaction = "Not Done";
            }
            return RedirectToAction("ScanFMDocumentsDone", new { DocketNo = DocketNo, Tranxaction = Tranxaction });
        }

        public ActionResult ScanFMDocumentsDone(string DocketNo, string Tranxaction)
        {
            List<Webx_FM_Scan_Documents> FMScan = new List<Webx_FM_Scan_Documents>();
            FMScan = DS.GetFMDetailByDocNo(DocketNo);
            ViewBag.Tranxaction = Tranxaction;
            return View(FMScan);
        }

        private string GetFileName(string fileName, string docno, string pref)
        {
            string strRet = fileName;

            string pat = @"(?:.+)(.+)\.(.+)";
            Regex r = new Regex(pat);
            //run
            Match m = r.Match(fileName);
            string file_ext = m.Groups[2].Captures[0].ToString();
            string filename = m.Groups[1].Captures[0].ToString();
            docno = docno.Replace("/", "$");

            strRet = pref + "_" + docno + "." + file_ext;

            return strRet;
        }

        private bool CheckDocumentExistance(string FileName)
        {
            try
            {
                return true;//File.Exists(Server.MapPath("~") + @"\GUI\Scan_Document\Vendor_Invoice_Scan" + FileName);
            }
            catch (Exception)
            {
                return true;
            }
        }

        #endregion

        #region Forward FM Document

        public ActionResult ForwardFMDocumentsQuery()
        {
            WebX_FM_FWD_DOC_MasterViewModel WFFDMVM = new WebX_FM_FWD_DOC_MasterViewModel();
            WFFDMVM.WFFDM = new WebX_FM_FWD_DOC_Master();
            WFFDMVM.WFFDM.FM_Entry_Date = System.DateTime.Now;
            WFFDMVM.FFDFM = new FM_FWD_DOCFilter();
            WFFDMVM.ListWFFDM = new List<WebX_FM_FWD_DOC_Master>();
            return View(WFFDMVM);
        }

        public JsonResult GetPaybseByDoctype(string CodeType, string searchTerm)
        {
            List<Webx_Master_General> ListPaybase = new List<Webx_Master_General>();
            ListPaybase = MS.GetGeneralMasterObject().Where(c => c.CodeType == CodeType && c.StatusCode == "Y").ToList();//.Where(c => c.CodeId.ToUpper().Contains(searchTerm.ToUpper()) || c.CodeType.ToUpper().Contains(searchTerm.ToUpper())).ToList().OrderBy(c => c.CodeType)
            if (CodeType != "BILLTYP")
            {
                Webx_Master_General objTax = new Webx_Master_General();
                objTax.CodeId = "All";
                objTax.CodeDesc = "ALL";
                ListPaybase.Insert(0, objTax);
            }
            var SearchList = (from e in ListPaybase
                              select new
                              {
                                  Value = e.CodeId,

Fleet/Views/Document/DocumentsTrack.cshtml
@model Fleet.ViewModels.DocumentTrackViewModel
@{
    ViewBag.Title = "Documents Track";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<SelectListItem> DocTypelist = new List<SelectListItem>(){
                    new SelectListItem{ Text="Bill", Value = "2" },
                    new SelectListItem{ Text="COD/DOD", Value = "4" },
                    new SelectListItem{ Text="POD", Value = "1" },
    };
}
@using (Html.BeginForm("TrackDocList", "Document", FormMethod.Post, new { id = "submit_form", @class = "form-horizontal row-fluid", enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-md-6">
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-list"></i>&nbsp;@ViewBag.Title
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="form-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-md-3">
                                        DocType :
                                    </label>
                                    <div class="col-md-6">
                                        @Html.DropDownListFor(c => c.DTF.DocType, new SelectList(DocTypelist, "Value", "Text"), "", new { @class = "form-control required required2 select2", @placeholder = "Select Doc Type" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-md-3" style="text-align:right">
                                        Document No :
                                    </label>
                                    <div class="col-md-6 text-primary margin-top-5">
                                        @Html.TextBoxFor(c => c.DTF.DocNo, new { @placeholder = "Document No", @class = "form-control required required2" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions fluid">
                        <div class="col-md-offset-3 col-md-8">
                            <button type="button" id="btnSubmit" class="btn btn-sm green controls ClsbtnSave"><i class="fa fa-check"></i>&nbsp;Get List</button>
                            <button type="button" id="btnXls" class="btn btn-sm green controls ClsbtnSave"><i class="fa fa-list"></i>&nbsp;Download XLS</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<div class="row" id="list">
    <div class="col-md-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-list"></i>Document Track List
                </div>
            </div>
            <div class="portlet-body form">
                <div class="form-body" id="tblData">
                    @{Html.RenderPartial("_DocumentsTrackList", Model.ListVWFTR);}
                </div>
            </div>
        </div>
    </div>
</div>

@*<div class="row">
    <div class="col-md-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-list"></i>Document Summary
                </div>
            </div>
            <div class="portlet-body form">
                <div class="form-body" id="tblData">
                    @{Html.RenderPartial("_DocumentsTrackSummary", Model.ListVWFTR);}
                    </div>
                </div>
            </div>
        </div>
    </div>*@

<script type="text/javascript">

    var FormComponents = function (DomainName) {

        var FormValidate = function (DomainName) {
            var form1 = $('#submit_form');
            var error1 = $('.alert-danger', form1);
            var success1 = $('.alert-success', form1);
            $.validator.addMethod('checkDCRSeriesAvailability', function (value, element) {
                //alert(value +  "   " + JSON.stringify(element))

                var DocType = $("#DTF_DocType").val();
                var DocNO = $("#DTF_DocNo").val();
                var DocumentNo = "";
                var StrURL = DomainName + "/Document/CheckDocno?DocNo=" + DocNO + "&DocType=" + DocType;
                // alert("hello " + StrURL);
                var result1 = $.ajax({
                    async: false,
                    type: 'POST',
                    contentType: 'application/json; charset=utf-8',
                    url: StrURL,
                    dataType: 'json',
                    data: {},
                });
                var d1 = JSON.parse(result1.responseText);

                // App.unblockUI();
                if (d1.CNT == "1") {
                    return true;
                }
                else {

                    return false;
                }
            }, "Document Number is Not Exist !!!");
            form1.validate({
                doNotHideMessage: true,
                errorElement: 'span', //default input error message container
                errorClass: 'help-block', // default input error message class
                // errorClass: 'validate-inline',
                focusInvalid: false, // do not focus the last invalid input


                rules: {
                    //account dateFuture
                },
                messages: {

                },
                invalidHandler: function (event, validator) { //display error alert on form submit
                    success1.hide();
                    error1.show();
                    App.scrollTo(error1, -200);
                },
                highlight: function (element) { // hightlight error inputs
                    $(element)
                        .closest('.form-group').addClass('has-error'); // set error class to the control group
                },
                unhighlight: function (element) { // revert the change done by hightlight
                    $(element)
                        .closest('.form-group').removeClass('has-error'); // set error class to the control group
                },
                success: function (label) {
                    label
                        .closest('.form-group').removeClass('has-error'); // set success class to the control group
                },
                submitHandler: function (form) {
                    success1.show();
                    error1.hide();
                }
            });
        }
        return {
            //main function to initiate the module
            init: function (DomainName) {
                FormValidate(DomainName);
                //$("#DTF_DocNo").change(function () {
                //    App.blockUI({ boxed: true });
                //    if ($("#DTF_DocType").val()!=2){
                //    $(this).rules("add", {
                //        checkDCRSeriesAvailability: true,
                //    });
                //    }
                //    App.unblockUI();
                //    }); FormValidate(DomainName);
                
                $("#list").hide();
                $("#btnSubmit").click(function (e) {
                    FormValidate(DomainName);
                    if (!$('#submit_form').valid()) {
                        App.unblockUI();
                        return;
                    }
                    else {
                        App.blockUI({ boxed: true });
                        var Doctype = $("#DTF_DocType").val();
                        var DocNo = $("#DTF_DocNo").val();
                        var strUrl = DomainName + '/Document/TrackDocList?Doctype=' + Doctype + '&DocNo=' + DocNo;
                        $.ajax({
                            url: strUrl,
                            cache: false,
                            data: {},
                            type: 'POST',
                            success: function (data) {
                                $("#list").show();
                                $('#TrackDocList').dataTable({
                                    "bDestroy": true
                                }).fnDestroy();
                                $("#TrackDocList").html(data);
                                App.unblockUI();
                                $("input:checkbox, input:radio").uniform();
                                initTableById("TrackDocList");
                            },
                            error: function (req, status, error) {
                                TosterNotification("error", 'Opration fail..!! There is some issue please try agian or Contact your administrator for more detail.', "Oppps..!!");
                                App.unblockUI();
                            }
                        });
                    }
                });
            }
        }
    }();
</script>

Fleet/Views/Document/FMReportQuery.cshtml
@model Fleet.ViewModels.FMFilter
@{
    ViewBag.Title = "FM Report Query";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("FMReport", "Document", FormMethod.Post, new { id = "form_sample", @class = "form-horizontal row-fluid", enctype = "multipart/form-data" }))
{
    { Html.RenderPartial("../UserControls/_FMQuery", Model); }
}

@*<script>
    var FormComponents = function (DomainName) {
        var Formvalidate = function (DomainName) {
            var form1 = $('#form_sample');
            var error1 = $('.alert-danger', form1);
            var success1 = $('.alert-success', form1);

            form1.validate({
                doNotHideMessage: true,
                errorElement: 'span', //default input error message container
                errorClass: 'help-block', // default input error message class
                // errorClass: 'validate-inline',
                focusInvalid: false, // do not focus the last invalid input
                ignore: "",

                rules: {
                    //account dateFuture
                },
                messages: {

                },
                invalidHandler: function (event, validator) { //display error alert on form submit
                    success1.hide();
                    error1.show();
                    App.scrollTo(error1, -200);
                },
                highlight: function (element) { // hightlight error inputs
                    $(element)
                        .closest('.form-group').addClass('has-error'); // set error class to the control group
                },
                unhighlight: function (element) { // revert the change done by hightlight
                    $(element)
                        .closest('.form-group').removeClass('has-error'); // set error class to the control group
                },
                success: function (label) {
                    label
                        .closest('.form-group').removeClass('has-error'); // set success class to the control group
                },
                submitHandler: function (form) {
                    success1.show();
                    error1.hide();
                    var form = $('#form_sample');
                    if (form.valid() == false) {
                        return false;
                    }
                }
            });
        }
        var Events = function (DomainName) {
            handleDateRangePickers('reportrange', 'FromDate', 'ToDate');
        }
        return {
            //main function to initiate the module
            init: function (DomainName) {
                FormValidate(DomainName);
                $("#dkttype").hide();
                $("#DocType").removeClass("required required2");
                Events(DomainName);
            }
        }
    }();
</script>*@

Fleet/Views/Document/ForwardFMAckDocumentsDone.cshtml
@model Fleet.ViewModels.vw_FM_DOC_For_AckViewModel
@{
    ViewBag.Title = "Forward FM Ack Documents";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.Status.ToUpper() == "1")
{
    <div class="col-md-offset-3 col-md-6" style="margin-top:10%;">
        <div class="portlet box @ViewBag.TableBoxColor">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-check"></i>@ViewBag.Title is Successfully @ViewBag.Tranxaction
                </div>
            </div>
            <div class="portlet-body">
                <div class="margin-top-10 margin-bottom-10 clearfix">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th class="center">
                                    FM No.
                                </th>
                                <th class="center">
                                    FM Type
                                </th>
                                <th class="center">
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var em in Model.ListVWFDFAM)
                            {
                                <tr>
                                    <td class="center">
                                        @em.fm_no
                                    </td>
                                    <td class="center">
                                        @em.FMType
                                    </td>
                                    <td class="center">
                                         
                                        <a href="@Url.Action("PFM_View_Print_Report", "ViewPrint", new { PFMNo = @ViewBag.FmNo})" onclick="window.open(this.href, 'Fleet','left=20,top=20,width=1240,height=620,toolbar=1,resizable=0'); return false;" id="ReportFrame"><b>View|Print</b></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <span class="label label-danger">
                    NOTE!
                </span>&nbsp;
                <span>
                    <span class="text-primary">Click Here <i class="fa fa-long-arrow-right"></i> </span>
                    <a href="@Url.Content("~/Document/AcknowledgeFMDocumentsQuery")"> Acknowledge documents</a> |
                    <a href="@Url.Content("~/Document/ForwardFMDocumentsQuery")"> Forward  Document</a> |
                    <a href="@Url.Content("~/Document/ScanFMDocuments")"> Scan Document</a>
                </span>
            </div>
        </div>
    </div>
}
else if (ViewBag.Tranxaction.ToUpper() == "NOT DONE")
{
    <div class="col-md-offset-3 col-md-6">
        <div class="alert alert-block alert-danger fade in center">
            <h2 class="alert-heading">Opps! Transaction fail</h2>
            <h4>
                FM No. <b>@ViewBag.FMNo</b> Can not Acknowledge without information of Manual FM No,Courier Name,Way Bill No and Way Bill Date.
            </h4>
        </div>
    </div>
}
else
{
    <div class="col-md-offset-3 col-md-6">
        <div class="alert alert-block alert-danger fade in center">
            <h2 class="alert-heading">Opps! @ViewBag.Title fail</h2>
            <h4>
                There is some issue with process. <br />Please check your internet connection else contact your administrator or service provider.
            </h4>
        </div>
    </div>
}

Fleet/Views/Document/PendingScanReport.cshtml
@model Fleet.ViewModels.FMFilter
@using System.Configuration
@using MvcReportViewer;
@{
    ViewBag.Title = "Pending Scan Report";
    Layout = null;
}

@{
    var parameters = new List<KeyValuePair<string, object>>
   {

       new KeyValuePair<string, object>("DocType", @Model.DocType),
       new KeyValuePair<string, object>("Ro", @Model.RO),
       new KeyValuePair<string, object>("Loc", @Model.Loccode),
       new KeyValuePair<string, object>("FromDT", @Model.FromDate),
       new KeyValuePair<string, object>("ToDT", @Model.ToDate),
   };

    var ReportPathPrefix = ConfigurationManager.AppSettings["ReportPathPrefix"].ToString();

}
<div id="divPrint">
    @if (Model.DocType == "1")
    {

        @Html.MvcReportViewer(ReportPathPrefix + "/Doc_Yet_To_Scan_POD", parameters, new { Height = 600, Width = "100%", style = "border: none" })
    }
    else
    {
        @Html.MvcReportViewer(ReportPathPrefix + "/Doc_Yet_To_Scan", parameters, new { Height = 600, Width = "100%", style = "border: none" })
    }


    <div class="span3"></div>
</div>

Fleet/Views/Document/PendingScanReportQuery.cshtml
@model Fleet.ViewModels.FMFilter
@{
    ViewBag.Title = "Pending Scan Report Query";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("PendingScanReport", "Document", FormMethod.Post, new { id = "form_sample", @class = "form-horizontal row-fluid", enctype = "multipart/form-data" }))
{
    {Html.RenderPartial("../UserControls/_FMQuery", Model);}
}

<script>
    var FormComponents = function (DomainName) {
        var Formvalidate = function (DomainName) {
            var form1 = $('#form_sample');
            var error1 = $('.alert-danger', form1);
            var success1 = $('.alert-success', form1);

            form1.validate({
                doNotHideMessage: true,
                errorElement: 'span', //default input error message container
                errorClass: 'help-block', // default input error message class
                // errorClass: 'validate-inline',
                focusInvalid: false, // do not focus the last invalid input
                ignore: "",

                rules: {
                    //account dateFuture
                },
                messages: {

                },
                invalidHandler: function (event, validator) { //display error alert on form submit
                    success1.hide();
                    error1.show();
                    App.scrollTo(error1, -200);
                },
                highlight: function (element) { // hightlight error inputs
                    $(element)
                        .closest('.form-group').addClass('has-error'); // set error class to the control group
                },
                unhighlight: function (element) { // revert the change done by hightlight
                    $(element)
                        .closest('.form-group').removeClass('has-error'); // set error class to the control group
                },
                success: function (label) {
                    label
                        .closest('.form-group').removeClass('has-error'); // set success class to the control group
                },
                submitHandler: function (form) {
                    success1.show();
                    error1.hide();
                    var form = $('#form_sample');
                    if (form.valid() == false) {
                        return false;
                    }
                }
            });
        }
        var Events = function (DomainName) {
            handleDateRangePickers('reportrange', 'FromDate', 'ToDate');
        }
        return {
            //main function to initiate the module
            init: function (DomainName) {
                FormValidate(DomainName);
                $("#FM").hide();
                Events(DomainName);
                $("#RO").on("change", function () {
                    var Id = $("#RO option:selected").val();
                    var strurl = DomainName + '/Document/SearchLocationListJsonByRO/' + Id;
                    FillDropDownfromOther('Loccode', strurl, false);
                });
            }
        }
    }();
</script>

Fleet/Views/Document/_DocumentsTrackList.cshtml
@model IEnumerable<FleetDataService.Models.VW_FM_TRACK_Report>

<table class="table table-striped table-bordered table-hover" id="TrackDocList" style="overflow-x: scroll">
        <thead>
            <tr>
                <th class="center">PFM No.</th>
                <th class="center">PFM Date</th>
                <th class="center">From</th>
                <th class="center">To</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ToList())
            {
                <tr>
                    <td class="center">
                        @Html.HiddenFor(m => @item.fm_no)
                        <a href="@Url.Action("PFM_View_Print_Report", "ViewPrint", new { PFMNo = @ViewBag.FmNo})" onclick="window.open(this.href, 'Fleet','left=20,top=20,width=1240,height=620,toolbar=1,resizable=0'); return false;" id="PFMNo" class="btnPFMNo"><b>@item.fm_no</b></a>
                    </td>
                    <td class="center">
                        @item.fmdt
                    </td>
                    <td class="center">
                        @item.fromloc
                    </td>
                    <td class="center">
                        @item.toLoc
                    </td>
                </tr>
            }
        </tbody>
    </table>