Fleet/Controllers/FixAssetsController.cs
using CipherLib;
using Fleet.Classes;
using Fleet.Filters;
using Fleet.ViewModels;
using FleetDataService;
using FleetDataService.Models;
using FleetDataService.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Serialization;
using WebMatrix.WebData;
using Fleet.Models;
using CYGNUS.Classes;

namespace Fleet.Controllers
{
    [Authorize]
    [NoDirectAccess]
    public class FixAssetsController : BaseController
    {
        FleetDataService.FixAssetService FAS = new FleetDataService.FixAssetService();
        FleetDataService.OperationService OS = new FleetDataService.OperationService();
        FleetDataService.ContractService CS = new FleetDataService.ContractService();
        PaymentService PS = new PaymentService();
        GeneralFuncations GF = new GeneralFuncations();

        public ActionResult FixAssets()
        {
            return View();
        }

        #region Fix Asset Master

        public ActionResult FixAssetMaster()
        {
            FixAssetsMasterViewModel objFixAssetMaster = new FixAssetsMasterViewModel();
            return View("FixAssetMaster", objFixAssetMaster);
        }

        public ActionResult GetMaster(string AccestCode)
        {
            WebxAssetmaster objAsset = new WebxAssetmaster();
            try
            {
                if (AccestCode != "0")
                {
                    string SQRY = "select UNITS as units,CATEGORY as category,ASSETCD as assetcd,* from webx_assetmaster where assetcd='" + AccestCode + "'";

                    DataTable Dt1 = GF.GetDataTableFromSP(SQRY);
                    List<WebxAssetmaster> AccountList = DataRowToObject.CreateListFromTable<WebxAssetmaster>(Dt1);
                    objAsset = AccountList.FirstOrDefault();
                }

            }
            catch (Exception)
            {

            }
            return PartialView("_AddEditFixAssetMaster", objAsset);
        }

        public JsonResult GetAssectByGroup(string AccountCode, string AccountGroup)
        {
            List<WebxAssetmaster> ObjWebxMaster = new List<WebxAssetmaster>();

            if (AccountCode != null)
            {
                ObjWebxMaster = FAS.GetAccountWiseRecord(AccountGroup, AccountCode);
                int autoid = 0;
                foreach (var item in ObjWebxMaster)
                {
                    autoid++;
                    item.Id = autoid;

                    if (item.units == "1")
                    {
                        item.units = "Nos.";
                    }
                    else if (item.units == "2")
                    {
                        item.units = "Kgs.";

                    }
                    else if (item.units == "3")
                    {
                        item.units = "Meter";

                    }
                    else if (item.units == "4")
                    {
                        item.units = "Liter";

                    }

                    if (item.category == "1")
                    {
                        item.category = "Movable";

                    }
                    else if (item.category == "2")
                    {
                        item.category = "Non-Movable";

                    }

                }
            }
            var data = (from e in ObjWebxMaster
                        select new
                        {
                            e.Id,
                            e.assetcd,
                            e.assetname,
                            e.units,
                            e.Groupcd,
                            e.category
                        }).ToArray();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AddEditMaster(WebxAssetmaster WebxMaster)
        {
            bool Status = false;
            try
            {
                DataTable dt = FAS.InsertUpdateAccount(WebxMaster.srno, WebxMaster.DEPMETHOD, WebxMaster.DEPRATE, WebxMaster.assetname, WebxMaster.GRPASSTCD, WebxMaster.units, WebxMaster.category, BaseUserName, WebxMaster.prefix, WebxMaster.assetcd, GF.FormateDate(WebxMaster.ExpiryDate));
                Status = true;
                return Json(Status, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(Status, JsonRequestBehavior.AllowGet);
            }
        }

        #endregion

        #region Purchase_Order

        public ActionResult PurchaseOrder()
        {
            POOrderViewModel objViewModel = new POOrderViewModel();
            List<WebxPOASSET_det> POASSECTList = new List<WebxPOASSET_det>();
            WebxPOASSET_det objPOASSECT = new WebxPOASSET_det();
            objPOASSECT.Id = 1;
            POASSECTList.Add(objPOASSECT);
            objViewModel.ListPO = POASSECTList;
            objViewModel.podate = System.DateTime.Now;
            objViewModel.qutdate = System.DateTime.Now;
            objViewModel.reqdt = System.DateTime.Now;
            return View("PurchaseOrder", objViewModel);
        }

        public ActionResult ADDPoOrder(int id)
        {
            WebxPOASSET_det ObjPO = new WebxPOASSET_det();
            ObjPO.Id = id;

            return PartialView("_Partial_PurchaseOrder", ObjPO);
        }


        public ActionResult FAPurchaseOrderSubmit(POOrderViewModel objViewModel, List<WebxPOASSET_det> PoList, PaymentControl ObjPayment, HttpPostedFileBase[] files)
        {
            string pocd = "";
            string extension = "", UserFileName = "", Documentpath = "";
            try
            {

                #region   PO Images Upload
                try
                {
                    if (((System.Web.HttpPostedFileBase[])(files)) != null)
                    {
                        foreach (var fileobj in files)
                        {
                            var file = ((System.Web.HttpPostedFileBase[])(files));
                            if (fileobj.ContentLength > 0)
                            {
                                string directory = "";

                                directory = @"D:\SRLApplicationCode\POD\PurchaseOrder\";
                                extension = System.IO.Path.GetExtension(fileobj.FileName);
                                //UserFileName = BaseUserName + extension;
                                UserFileName = objViewModel.VENDORCD + "_" + System.DateTime.Now.ToString("dd_MM_yyyy_HH_mm_ss_tt") + "_" + fileobj.FileName;
                                //    Documentpath = Server.MapPath("D:/SRLApplicationCode/POD/OtherBillEntry/") + UserFileName;
                                //  string strDirectoryName = Server.MapPath("D:/SRLApplicationCode/POD/OtherBillEntry/");

                                fileobj.SaveAs(Path.Combine(directory, UserFileName));

                                if (Directory.Exists(directory) == false)
                                    Directory.CreateDirectory(directory);
                                // fileobj.SaveAs(Documentpath);

                            }

                        }
                    }
                }
                catch (Exception ex)
                {
                    // DocumentUploadedPath = Em.Elec_Expense_DET.b;
                }

                #endregion




                objViewModel.podate = Convert.ToDateTime(GF.FormateDate((objViewModel.podate)));
                objViewModel.Documentpath = UserFileName;
                XmlDocument xmlDoc = new XmlDocument();
                XmlSerializer xmlSerializer = new XmlSerializer(objViewModel.GetType());
                using (MemoryStream xmlStream = new MemoryStream())
                {
                    xmlSerializer.Serialize(xmlStream, objViewModel);
                    xmlStream.Position = 0;
                    xmlDoc.Load(xmlStream);
                }

                string XML_Det = "<root>";
                foreach (var item in PoList)
                {
                    XML_Det = XML_Det + "<WebxPOASSET_det>";
                    XML_Det = XML_Det + "<podate>" + GF.FormateDate(objViewModel.podate) + "</podate>";
                    XML_Det = XML_Det + "<assetcd>" + item.assetcd + "</assetcd>";
                    XML_Det = XML_Det + "<qty>" + item.qty + "</qty>";
                    XML_Det = XML_Det + "<rate>" + item.rate + "</rate>";
                    XML_Det = XML_Det + "<narration>" + item.narration + "</narration>";
                    XML_Det = XML_Det + "<tax_per>" + item.tax_per + "</tax_per>";
                    XML_Det = XML_Det + "<OtherCharge>" + item.OtherCharge + "</OtherCharge>";
                    XML_Det = XML_Det + "<total>" + item.total + "</total>";
                    XML_Det = XML_Det + "<HSN_SAC>" + item.HSN_SAC + "</HSN_SAC>";
                    XML_Det = XML_Det + "<taxableAmt>" + item.taxableAmt + "</taxableAmt>";
                    XML_Det = XML_Det + "<TaxAmount>" + item.TaxAmount + "</TaxAmount>";
                    XML_Det = XML_Det + "</WebxPOASSET_det>";
                }
                XML_Det = XML_Det + "</root>";
                DataTable dtPOList = FAS.InsertFAPoList(xmlDoc.InnerXml, XML_Det.ReplaceSpecialCharacters(), BaseUserName, BaseLocationCode, BaseFinYear);

                if (dtPOList.Rows[0][0].ToString() == "Done" && dtPOList.Rows[0][1].ToString() == "1")
                {
                    pocd = dtPOList.Rows[0][2].ToString();
                }
                else
                {
                    ViewBag.StrError = "Error ! Some issue in generation.";
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.StrError = "Error " + ex.Message.ToString().Replace('\n', '_');

Fleet/Views/FixAssets/AssectAssignViewPrintList.cshtml
@model FleetDataService.ViewModels.BABillEnty
@using Fleet
@using Fleet.ViewModels
@{
    ViewBag.Title = "AssectAssignViewPrintList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="portlet @ViewBag.TableBoxColor box">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-list"></i>Assign Assets List
        </div>
    </div>
    <div class="portlet-body">
        @using (Html.BeginForm("", "", FormMethod.Post, new { id = "form_sample", @class = "form-horizontal row-fluid", enctype = "multipart/form-data" }))
        {
            <div class="form-body">
                <div class="alert alert-danger display-hide">
                    <button class="close" data-close="alert"></button>
                    You have some form errors. Please check below.
                </div>

                <div class="alert alert-success display-hide">
                    <button class="close" data-close="alert"></button>
                    Your form validation is successful!
                </div>
                <div class="portlet-body clsMF flip-scroll">
                    <table class="table table-bordered table-striped table-condensed flip-content">
                        <thead class="flip-content">
                            <tr>
                                @*<th>
                                    <input type="checkbox" id="IsAllEnabledPO" />
                                </th>*@
                                <th class="center">
                                    Asset Code
                                </th>
                                <th class="center">
                                    GRN Code
                                </th>
                                <th class="center">
                                    GRN Date
                                </th>
                                <th class="center">
                                    Asset Name
                                </th>
                                <th class="center">
                                    Current Location
                                </th>
                                <th class="center">
                                    View
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var itm in Model.POList)
                            {
                                Html.RenderPartial("_ASSETASSIGNVIEWPRINT", itm);
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="form-actions fluid">
                <div class="col-md-offset-4 col-md-8">
        
                    <a class="btn btn-sm default controls" href="@Url.Action("AssetAssignCretiraViewPrint", "FixAssets")"> <i class="fa fa-arrow-left"> </i>&nbsp;Back To Criteria</a>
                    @*@if (Model.POList.Count > 0)
                    {
                        <button type="button" id="btnSubmit" class="btn btn-sm green controls" disabled="disabled"><i class="fa fa-check"></i>&nbsp;Submit</button>
                    }*@
                </div>
            </div>
        }
    </div>
</div>
<script>
    var FormComponents = function (DomainName) {

        var Formvalidate = function (DomainName) {

            var form1 = $('#form_sample');
            var error1 = $('.alert-danger', form1);
            var success1 = $('.alert-success', form1);

            form1.validate({
                doNotHideMessage: true,
                errorElement: 'span', //default input error message container
                errorClass: 'help-block', // default input error message class
                // errorClass: 'validate-inline',
                focusInvalid: false, // do not focus the last invalid input
                messages: {


                    //'ServiceFor': {
                    //    required: "Please select at least one service for option",
                    //    minlength: jQuery.format("Please Select at Least One Service For Option")
                    //}
                },
                errorPlacement: function (error, element) { // render error placement for each input type
                    //if (element.parents('.checkbox-list').size() > 0) {
                    //    error.appendTo(element.parents('.checkbox-list').attr("data-error-container"));
                    //} else {
                    error.insertAfter(element); // for other inputs, just perform default behavior
                    //}
                },
                invalidHandler: function (event, validator) { //display error alert on form submit
                    success1.hide();
                    error1.show();
                    App.scrollTo(error1, -200);
                },
                highlight: function (element) { // hightlight error inputs
                    $(element)
                        .closest('.form-group').addClass('has-error'); // set error class to the control group
                },
                unhighlight: function (element) { // revert the change done by hightlight
                    $(element)
                        .closest('.form-group').removeClass('has-error'); // set error class to the control group
                },
                success: function (label) {
                    label
                        .closest('.form-group').removeClass('has-error'); // set success class to the control group
                },
                submitHandler: function (form) {
                    success1.show();
                    error1.hide();
                    //  form1.submit();
                }
            });
        }


        var SubmitClick = function (DomainName) {
            $('#btnSubmit').click(function () {
                var form = $('#form_sample');
                if (form.valid() == false) {
                    return false;
                }
                App.blockUI({ boxed: true });
                document.forms["form_sample"].submit();
            });
        }

        return {
            //main function to initiate the module
            init: function (DomainName) {
                Formvalidate(DomainName);
                SubmitClick(DomainName);
                $(".date").val('');
                $(".drp").select2({ allowClear: true });

                $('.date-picker').datepicker({
                    isRTL: App.isRTL(),
                    format: "dd M yyyy",
                    autoclose: true,

                    pickerPosition: (App.isRTL() ? "bottom-right" : "bottom-left"),
                    todayBtn: true
                });


                $("#IsAllEnabledPO").live('change', function () {
                    var checked = jQuery(this).is(":checked");

                    $(".clsPOCheck").each(function () {
                        if (checked) {
                            $("#btnSubmit").attr('disabled', false)
                            $(this).attr("checked", true);
                            $(this).parents('span').addClass("checked");
                            $(".req").addClass("required required2")
                        }
                        else {
                            $("#btnSubmit").attr('disabled', true)
                            $(this).attr("checked", false);
                            $(this).parents('span').removeClass("checked");
                            $(".req").removeClass("required required2")
                        }
                    });
                });
                $(".clsPOCheck").live('change', function () {
                    var checked = jQuery(this).is(":checked");
                    var itemIndex = $(this).attr("id").replace("AssectList_", "").replace("__IsEnabled", "");


                    if (checked) {

                        // $("#btnSubmit").attr('disabled', false)
                        $(this).attr("checked", true);
                        $(this).parents('span').addClass("checked");

                        $("#AssectList_" + itemIndex + "__AssignLoc").addClass("required required2")
                        $("#AssectList_" + itemIndex + "__desc").addClass("required required2")
                        $("#AssectList_" + itemIndex + "__DpartName").addClass("required required2")
                        $("#AssectList_" + itemIndex + "__InstallDate").addClass("required required2")
                        $("#AssectList_" + itemIndex + "__Employee").addClass("required required2")
                    }
                    else {
                        // $("#btnSubmit").attr('disabled', true)
                        $(this).attr("checked", false);
                        $(this).parents('span').removeClass("checked");

                        $("#AssectList_" + itemIndex + "__AssignLoc").removeClass("required required2")
                        $("#AssectList_" + itemIndex + "__desc").removeClass("required required2")
                        $("#AssectList_" + itemIndex + "__DpartName").removeClass("required required2")
                        $("#AssectList_" + itemIndex + "__InstallDate").removeClass("required required2")
                        $("#AssectList_" + itemIndex + "__Employee").removeClass("required required2")
                    }

                    var count = 0;
                    $('.clsPOCheck').each(function () {
                        if (this.checked) {
                            $("#IsAllEnabledPO").parent('span').removeClass('checked');
                            $("#btnSubmit").attr('disabled', false);
                            count = count + 1;
                        }
                    })
                    if (count == 0) {
                        $("#btnSubmit").attr('disabled', true);
                    }
                });

            }
        }
    }();
</script>

Fleet/Views/FixAssets/AssetSaleUtility.cshtml
@model FleetDataService.ViewModels.AssetUTILITYViewModel
@using Fleet.Models
@using Fleet.ViewModels
@using Fleet.Helpers
@using FleetDataService.Models;

@{
    ViewBag.Title = "Asset Sale Utility";
    Layout = "~/Views/Shared/_Layout.cshtml";

    FleetDataService.MasterService MS = new FleetDataService.MasterService();
    FleetDataService.FixAssetService FAS = new FleetDataService.FixAssetService();
    List<WEBX_GENERAL_ASSETMASTER> ASSETCODE = FAS.GetAssetCode();
    List<webx_location> locationList = MS.GetLocationDetails().Where(c => c.ActiveFlag == "Y").OrderBy(c => c.LocName).ToList();
}
@using (Html.BeginForm("AssetDumpUtilityCretiraList", "FixAssets", FormMethod.Post, new { id = "submit_form", @class = "form-horizontal row-fluid", enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-md-8">
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-filter"></i>Asset Sale Utility
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="form-body">
                        <div class="row">
                            <div class="col-md-10">
                                <div class="form-group">
                                    <label class="control-label col-md-3">
                                        Select  Date :
                                    </label>
                                    <div class="col-md-6">
                                        <div id="reportrange" class="btn default">
                                            <i class="fa fa-calendar"></i>
                                            &nbsp;
                                            <span></span>
                                            <b class="fa fa-angle-down"></b>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-10">
                                <div class="form-group">
                                    <label class="control-label col-md-3">
                                        Branch :
                                    </label>

                                    <div class="col-md-6">
                                        @Html.TextBoxFor(c => c.LocCode, new { placeholder = "Enter Branch", @class = "form-control" })
                                    </div>
                                    @Html.HiddenFor(c => c.FromDate)
                                    @Html.HiddenFor(c => c.ToDate)
                                    @Html.HiddenFor(c => c.ASSETTYPE)
                                </div>
                            </div>
                            <div class="col-md-10">
                                <div class="form-group">
                                    <label class="control-label col-md-3">
                                        Item Name
                                    </label>
                                    <div class="col-md-6">
                                        @Html.DropDownListFor(c => c.ITEMCODE, new SelectList(ASSETCODE, "ASSETCD", "ASSETNAME"), "", new { @class = "form-control select2 " })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions fluid">
                        <div class="row">
                            <div class="col-md-offset-5 col-md-10">
                                <button type="submit" id="btnSubmit" class="btn btn-sm blue controls"><i class="fa fa-search"></i>&nbsp;Search</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">

    var FormComponents = function (DomainName) {

        var Formvalidate = function (DomainName) {
            if (!jQuery().bootstrapWizard) {
                return;
            }

            var form = $('#submit_form');
            var error = $('.alert-danger', form);
            var success = $('.alert-success', form);

            form.validate({
                doNotHideMessage: true, //this option enables to show the error/success messages on tab switch.
                errorElement: 'span', //default input error message container
                errorClass: 'help-block', // default input error message class
                focusInvalid: false, // do not focus the last invalid input

                invalidHandler: function (event, validator) { //display error alert on form submit
                    success.hide();
                    error.show();
                    App.scrollTo(error, -200);
                },

                highlight: function (element) { // hightlight error inputs
                    $(element)
                        .closest('.form-group').removeClass('has-success').addClass('has-error'); // set error class to the control group
                },

                unhighlight: function (element) { // revert the change done by hightlight
                    $(element)
                        .closest('.form-group').removeClass('has-error'); // set error class to the control group
                },

                success: function (label) {
                    if (label.attr("for") == "gender" || label.attr("for") == "payment[]") { // for checkboxes and radio buttons, no need to show OK icon
                        label
                            .closest('.form-group').removeClass('has-error').addClass('has-success');
                        label.remove(); // remove error label here
                    } else { // display success icon for other inputs
                        label
                            .addClass('valid') // mark the current input as valid and display OK icon
                        .closest('.form-group').removeClass('has-error').addClass('has-success'); // set success class to the control group
                    }
                },

                submitHandler: function (form) {
                    success.show();
                    error.hide();
                    App.blockUI({ boxed: true });
                    document.forms["form_sample"].submit();
                }
            });
        }

        var handleDateRangePickers = function () {
            if (!jQuery().daterangepicker) {
                return;
            }
            $('#reportrange').daterangepicker({
                opens: (App.isRTL() ? 'left' : 'right'),
                startDate: moment().subtract('days', 29),
                endDate: moment(),
                //maxDate: '12/31/2014',
                showDropdowns: true,
                showWeekNumbers: true,
                timePicker: false,
                timePickerIncrement: 1,
                timePicker12Hour: true,
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                    'Last 7 Days': [moment().subtract('days', 6), moment()],
                    'Last 30 Days': [moment().subtract('days', 29), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                },
                buttonClasses: ['btn'],
                applyClass: 'green',
                cancelClass: 'default',
                format: 'DD/MM/YYYY',
                separator: ' to ',
                locale: {
                    applyLabel: 'Apply',
                    fromLabel: 'From',
                    toLabel: 'To',
                    customRangeLabel: 'Custom Range',
                    daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                    monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                    firstDay: 1
                }
            },

                 function (start, end) {
                     $('#FromDate').val(start.format('MMMM D, YYYY'));
                     $('#ToDate').val(end.format('MMMM D, YYYY'));
                     $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
                 }
            );
            $('#reportrange span').html(moment().subtract('days', 29).format('MMMM D, YYYY') + ' - ' + moment().format('MMMM D, YYYY'));
            $('#FromDate').val(moment().subtract('days', 29).format('MMMM D, YYYY'));
            $('#ToDate').val(moment().format('MMMM D, YYYY'));
        }

        return {
            //main function to initiate the module
            init: function (DomainName) {
                Formvalidate(DomainName);
                handleDateRangePickers();
                var StrURL = DomainName + "/FixAssets/GetReassignLocationsDetails";
                JsonDDLSelectCode("LocCode", StrURL);
            }
        }
    }();
</script>

Fleet/Views/FixAssets/AssignAssectDone.cshtml
@{
    ViewBag.Title = "POOrderDone";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-offset-3 col-md-6" style="margin-top:10%;">
    <div class="portlet box @ViewBag.TableBoxColor">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-check"></i> Assign Assect Done Sucessfully
            </div>
        </div>
        <div class="portlet-body">
            <div class="margin-top-10 margin-bottom-10 clearfix">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>
                                Goods Recipt Note
                            </th>

                            <th>
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <b>@ViewBag.GRN</b>

                            </td>

                            <td>
                                <a target="_blank" href="@Url.Action("ASSIGNASSET", "ViewPrint", new { GRNNO = ViewBag.GRN })" id="ReportFrame"><b>View</b></a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <span class="label label-danger">
                NOTE!
            </span>&nbsp;
            <span>
                Click Here <a href="@Url.Action("AssetAssignReassignCriteria", "FixAssets")"><b> To New Assign </b></a>
            </span>
        </div>
    </div>
</div>