Fleet/Controllers/ReportsController.cs
using Fleet.Classes;
using FleetDataService;
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Fleet.ViewModel;
using MvcReportViewer;

namespace Fleet.Controllers
{

    [Authorize]
    //[NoDirectAccess]
    public class ReportsController : BaseController
    {
        GeneralFuncations GF = new GeneralFuncations();
        ReportService CL = new ReportService();

        public ActionResult ReportList(string ReportType, string ReportSubType)
        {
            ViewBag.ReportType = ReportType;
            ViewBag.ReportSubType = ReportSubType;
            var ReportList = CL.GetReportList(ReportType, ReportSubType, BaseUserName.ToUpper(), 1);

            return View(ReportList);
        }

        public ActionResult Index(int Id)
        {
            StandardReportFilter RF = new StandardReportFilter();
            RF.ReportDetails = CL.GetReportDetails(Id);
            RF.ReportId = Id;
            RF.ParameterSet_Details = CL.GETParameterDetails(RF.ReportDetails.ParameterSetId);
            RF.ReportParameterSetId = RF.ReportDetails.ParameterSetId;
            RF.RDLName = RF.ReportDetails.RDLName;
            return View(RF);
        }

        public ActionResult ReportResult(StandardReportFilter RF, FormCollection FormData, bool isDownFormat)
        {
            //RF.ClientName = BaseClientName;
            RF.ParameterSet_Details = CL.GETParameterDetails(RF.ReportParameterSetId);
            StandardReportFilter[] StandardReportFilterList = new StandardReportFilter[1];
            StandardReportFilterList[0] = RF;
            DataTable DT = GF.GetDataTableFromObjects(StandardReportFilterList);

            var ReportParameterList = CL.GetReportParameters(RF.ReportId);

            List<ReportParameter> parameters = new List<ReportParameter>();

            foreach (var itm in RF.ParameterSet_Details.Where(c => c.IsRequiredInReport == true).ToList())
            {
                var ParameterNameList = ReportParameterList.Where(c => c.ReplaceParameterName == itm.ParameterName && c.IsDefaultParameter == false).ToList();

                string ParameterName = itm.ParameterName;

                if (ParameterNameList.Count() > 0)
                {
                    ParameterName = ParameterNameList.FirstOrDefault().ParameterName;
                }

                if (itm.ParameterType == 1)
                {
                    ReportParameter RPT = new ReportParameter("StartDate", GF.FormateDate(Convert.ToDateTime(FormData["StartDate"])));
                    parameters.Add(RPT);
                    ReportParameter RPT1 = new ReportParameter("EndDate", GF.FormateDate(Convert.ToDateTime(FormData["EndDate"])));
                    parameters.Add(RPT1);
                }
                if (itm.ParameterType == 7)
                {
                    ReportParameter RPT = new ReportParameter("Location", FormData["Location"]);
                    parameters.Add(RPT);
                    //ReportParameter RPT1 = new ReportParameter("LocationLevel", FormData["LocationLevel"]);
                    //parameters.Add(RPT1);
                    ReportParameter RPT2 = new ReportParameter("RO", FormData["RO"]);
                    parameters.Add(RPT2);   
                }
                if (itm.ParameterType == 12)
                {
                    ReportParameter RPT = new ReportParameter("LocationTo", FormData["LocationTo"]);
                    parameters.Add(RPT);
                    ReportParameter RPT1 = new ReportParameter("LocationLevelTo", FormData["LocationLevelTo"]);
                    parameters.Add(RPT1);
                }
                if (itm.ParameterType == 8 || itm.ParameterType == 9 || itm.ParameterType == 10 || itm.ParameterType == 11 || itm.ParameterType == 5 || itm.ParameterType == 13 || itm.ParameterType == 3)
                {
                    var ControlVal = FormData[itm.ParameterName].ToString();

                    if (ControlVal == "")
                        ControlVal = itm.BlankValue;

                    ReportParameter RPT1 = new ReportParameter(ParameterName, ControlVal);
                    parameters.Add(RPT1);
                }

                if (itm.ParameterType == 2) 
                {
                    if (itm.IsMultipleChoice)
                    {
                        //string strVal = FormData[itm.ParameterName].ToString();
                        //string[] strArray = null;
                        //if (strVal != null && strVal.Split(',').Count() > 0)
                        //{
                        //    strArray = strVal.Split(',');
                        //}

                        //ReportParameter RPT = new ReportParameter(ParameterName, strArray);
                        //parameters.Add(RPT);

                        ReportParameter RPT = new ReportParameter(ParameterName, FormData[itm.ParameterName].ToString());
                        parameters.Add(RPT);
                    }
                    else
                    {
                        ReportParameter RPT = new ReportParameter(ParameterName, FormData[itm.ParameterName].ToString());
                        parameters.Add(RPT);
                    }
                }
            }

            foreach (var itm in ReportParameterList.Where(c => c.IsDefaultParameter).ToList())
            {
                ReportParameter RPT = new ReportParameter(itm.ParameterName, itm.DefaultValue.ToString());
                parameters.Add(RPT);
            }

            RF.RDLparameters = parameters;

            if (RF.ReportId != 25 && RF.ReportId != 28 && RF.ReportId != 83 && RF.ReportId != 84 && RF.ReportId != 85 && RF.ReportId != 158)
                RF.RDLparameters = RF.RDLparameters.Where(c => c.Name != "ReportCategory").ToList();

            foreach (var item in parameters)
            {
                CL.InsertReportHistory(FormData["ReportId"], item.Name, item.Values[0], BaseUserName);
            }

            ViewBag.ReportId = RF.ReportId.ToString();


            if (RF == null)
            {
                return RedirectToAction("Index");
            }

            //if (isDownFormat)
            //{
            //    return DownloadReport(ReportFormat.Excel, RF.RDLparameters, FormData["RDLPATH"].ToString(), FormData["ReportDetails.DisplayName"]);
            //}

            return View(RF);
        }


        private ActionResult DownloadReport(ReportFormat format, List<ReportParameter> parameters, string RDLPath, string filename = null)
        {
            List<KeyValuePair<string, object>> keyValuePair = new List<KeyValuePair<string, object>>();

            foreach (ReportParameter RP in parameters)
            {
                string _parameterValues = "";
                foreach (var _values in RP.Values)
                {
                    if (_parameterValues == "")
                        _parameterValues = _values;
                    else
                        _parameterValues = _parameterValues + "," + _values;
                }
                KeyValuePair<string, object> newParam = new KeyValuePair<string, object>(RP.Name, _parameterValues);
                keyValuePair.Add(newParam);
            }

            filename = filename + " " + DateTime.Now.ToString("dd MMM yyyy hh mm ss");
            filename = filename.Replace(" ", "_") + ".csv";

            return this.Report(
                format,
                RDLPath,
                keyValuePair,
                filename: filename);
        }

        public JsonResult GetDynamicParameterValue(string SQRY)
        {
            List<ReportService.ReportParameterValue> list = CL.GetDynamicParameterValue(SQRY);

            return Json(list, JsonRequestBehavior.AllowGet);

        }

        #region Required Methods



        public ActionResult GetReportFields(string SQRY)
        {
            List<ReportService.ReportField> CMP = CL.GetReportFields(SQRY);

            return PartialView("_ReportFields", CMP);
        }


        public JsonResult GetEmployeeUserDriverVehicleList(string searchTerm, string SearchType)
        {
            var CMP = CL.GetCustomerListFromSearch(searchTerm, SearchType);

            var users = from user in CMP

                        select new
                        {
                            id = user.CUSTCD,
                            text = user.CUSTNM
                        };

            return Json(users, JsonRequestBehavior.AllowGet);
        }


        #endregion
    }
}

Fleet/Views/Reports/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Fleet.ViewModel.StandardReportFilter

<div class="row">
    <div class="col-md-10">
        <div class="portlet box @ViewBag.TableBoxColor ">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-filter"></i>@Model.ReportDetails.ReprotName
                </div>
                <div class="caption pull-right">
                    <a href="@Url.Content("~/Reports/ReportList?ReportType=" + Model.ReportDetails.ReportType + "&ReportSubType=" + Model.ReportDetails.ReportSubType)" class="btn btn-xs default backButton">
                        <i class="fa fa-arrow-left"></i>&nbsp;Back to Report List
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="form-body">

                    @using (Html.BeginForm("ReportResult", "Reports", FormMethod.Post, new { @id = "submit_form", @class = "form-horizontal" }))
                    {
                        <div class="alert alert-danger display-hide">
                            <button class="close" data-close="alert"></button>
                            You have some form errors. Please check below.
                        </div>
                        <div class="alert alert-success display-hide">
                            <button class="close" data-close="alert"></button>
                            Your form validation is successful!
                        </div>
                        {
                            Html.RenderPartial("../UserControls/_StandardReportFilte", Model);
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Fleet/Views/Reports/PODPFMFlow.cshtml
@{
    ViewBag.Title = "PODPFMFlow";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model  ReportPortal.ViewModel.ReportsViewModel

<div id="loading" style="display: none;">
    <img src="@Url.Content("~/assets/img/loading.gif")" />
</div>
<div class="col-md-10">
    <div class="portlet box @ViewBag.TableBoxColor ">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-reorder"></i> PO Entry
            </div>
        </div>
        <div class="portlet-body form">
            @using (Html.BeginForm("PODPFMFlow", "Reports", FormMethod.Post, new { @id = "form_sample", @class = "form-horizontal" }))
            {
              
                    Html.RenderPartial("../UserControls/_BasicReportQuery", Model);
                
            }
        </div>
    </div>
</div>

Fleet/Views/Reports/ReportList.cshtml
@{
    ViewBag.Title = @ViewBag.ReportSubType + " Report List";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var i = 1;
}

@model IEnumerable<FleetDataService.Models.CYGNUS_Master_Reports>

<div class="portlet @ViewBag.TableBoxColor box">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-edit"></i>@ViewBag.Title
        </div>
    </div>
    <div class="portlet-body">

        <table id="sample_ven" class="table table-striped table-bordered table-hover">
            @if (Model.Count() > 0)
            {
                <thead>
                    <tr>
                        <th class="center">Sr. No.</th>
                        <th>Report Name</th>
                        <th>Desription</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        MvcHtmlString ReportName = MvcHtmlString.Create(item.DisplayName);
                        <tr>
                            <td class="center"><b>@i</b></td>
                            <td><a href="@Url.Content("~/Reports/Index/" + item.ID)">@ReportName</a></td>
                            <td>@item.Description</td>
                        </tr>
                        i++;
                    }

                </tbody>
            }
            else
            {
                <div class="note note-info">
                    <h4 class="block">Info! No Rights.</h4>
                    <h5>
                        You do not have permission to view any reports for @ViewBag.ReportSubType. Please contact your administrator or service provider.
                    </h5>
                </div>
            }
        </table>
    </div>
</div>
<script type="text/javascript">
    var FormComponents = function (DomainName) {
        return {
            init: function (DomainName) {
                $("a").live("click", function () {
                    App.blockUI({ boxed: true });
                });
            }
        };
    }();
</script>

Fleet/Views/Reports/ReportResult.cshtml
@{
    ViewBag.Title = "ReportResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using MvcReportViewer;
@using Microsoft.Reporting.WebForms;
@using System.Web.UI.WebControls
@model Fleet.ViewModel.StandardReportFilter
@using FleetDataService.Models
@using Fleet.Classes
@using System.Data
@{
    var CS = new ControlSettings
    {
        ShowParameterPrompts = Model.ReportDetails.ShowParameterPrompts,
        ShowFindControls = Model.ReportDetails.ShowFindControls,
        BackColor = System.Drawing.Color.LightGray,
        KeepSessionAlive = true,
        Width = new Unit("100%"),
        Height = new Unit("800px"),
        SizeToReportContent = true,
        AsyncRendering = false,
        //  ShowReportBody=false,
        ShowToolBar = Model.ReportDetails.ShowToolBar
    };

    string RDLPATH = ViewBag.StandardReportPath + "/" + Model.RDLName;

    //if (Model.ReportParameterSetId == 2)
    //{
    //    RDLPATH = "/" + ViewBag.StandardReportPath + "/RouteWise_Vehiclewise_TotalTravel_Report";

    //}


    GeneralFuncations GF = new GeneralFuncations();

    string SQRY = "SELECT * FROM CYGNUS_Master_Reports WITH(NOLOCK) WHERE ID = '" + ViewBag.ReportId.ToString() + "'";
    DataTable Dt1 = GF.getdatetablefromQuery(SQRY);
    List<CYGNUS_Master_Reports> ReportMasterList = DataRowToObject.CreateListFromTable<CYGNUS_Master_Reports>(Dt1);
    CYGNUS_Master_Reports objReportMaster = new CYGNUS_Master_Reports();
    objReportMaster = ReportMasterList.FirstOrDefault();
}

<div class="form-body">
    <div class="row">
        <a href="@Url.Content("~/Reports/Index/"+@ViewBag.ReportId)" class="btn btn-sm blue backButton">
            <i class="fa fa-arrow-left"></i>&nbsp;Back to Criteria
        </a>
        <a href="@Url.Content("~/Reports/ReportList?ReportType=" + objReportMaster.ReportType + "&ReportSubType=" + objReportMaster.ReportSubType)" class="btn btn-sm blue backButton">
        <i class="fa fa-arrow-left"></i>&nbsp;Back to Report List
        </a>
    </div>
</div> 

@Html.MvcReportViewerFluent(RDLPATH).ReportParameters(Model.RDLparameters).Attributes(new { Height = 500, Width = new Unit("100%"), style = "border: none" }).ControlSettings(CS)

<script type="text/javascript">
    var FormComponents = function (DomainName) {
        return {
            init: function (DomainName) {
                $(".backButton").live("click", function () {
                    App.blockUI({ boxed: true });
                    //window.location = DomainName + "/Reports/Index/" + "@ViewBag.ReportId";
                });
            }
        };
    }();
</script>

Fleet/Views/Reports/Showreports.cshtml
@{
    ViewBag.Title = "Showreports";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using MvcReportViewer;
@using Microsoft.Reporting.WebForms;
@using System.Web.UI.WebControls


@model ReportPortal.ViewModel.ReportsViewModel

@{


    var CS = new ControlSettings
    {
        ShowParameterPrompts = true,
        ShowFindControls = false,
        BackColor = System.Drawing.Color.LightGray,
        //KeepSessionAlive = true,
        //Width = new Unit("100%"),
        //Height = new Unit("800px"),
        SizeToReportContent = false,
        //AsyncRendering = false,
        //  ShowReportBody=false,
        ShowToolBar = true
    };

    string RDLPATH = "/RCPL_TEST/DKT_PODPFM_FLOW";// +ViewBag.StandardReportPath + "/" + Model.RDLName;


    //List<ReportParameter> parameters1 = new List<ReportParameter>();
    //parameters1.Add(new ReportParameter("location", "All"));
    //parameters1.Add(new ReportParameter("locLevel", "1"));
    //parameters1.Add(new ReportParameter("Fromdt", "01 Apr 16"));
    //parameters1.Add(new ReportParameter("todt", "01 Apr 16"));
    //parameters1.Add(new ReportParameter("RPTYP", "2"));


    //var parameters2 = new List<KeyValuePair<string, object>>
    //{
    //    new KeyValuePair<string, object>("Fromdt",  "01 Apr 15"),
    //    new KeyValuePair<string, object>("todt",  "01 Apr 16"),
    //  //  new KeyValuePair<string, object>("RouteID", "21,22"),
    //  //new KeyValuePair<string, object>("Stop",140),
    //  // // new KeyValuePair<string, object>("THCNO", "SS")
    //};


}

@*@Html.MvcReportViewer(
                        RDLPATH,
                                             parameters1,
    new { Height = 600, Width = "100%", style = "border: none" })*@

@Html.MvcReportViewerFluent(RDLPATH).ReportParameters(Model.RDLparameters).Attributes(new { Height = 900, Width = new Unit("100%"), style = "border: none" }).ControlSettings(CS)


<script type="text/javascript">




    var FormComponents = function (DomainName) {


        return {
            //main function to initiate the module
            init: function (DomainName) {


            }
        };
    }();

</script>

Fleet/Views/Reports/_ReportFields.cshtml
@model  IEnumerable<FleetDataService.ReportService.ReportField>

@{


    string CurrReportHeader = "", PrevReportHeader = "";
}

<div class=" form-group ">
    @foreach (var item in Model)
    {
        CurrReportHeader = item.ReprotHeader;

        string subRptClass = "cls" + item.SubReportType;

        if ((PrevReportHeader == "") || CurrReportHeader != PrevReportHeader)
        {
            <div class="col-md-12 ">
                <b>    @item.ReprotHeader <label  ><input type="checkbox" name="ReportFieldsCHK1" id="@item.SubReportType.Replace(",", "")" value="@item.SubReportType.Replace(",", "")" class="clsReportFields"> <b> Select All </b></label>  </b>
            </div>
        }

        <div class="col-md-3  ">

            <label ><input type="checkbox" name="ReportFieldsCHK" id="@item.Value" value="@item.Value" class="clsReportFields1 @item.SubReportType.Replace(",", "") "> @item.Text</label>

        </div>


        PrevReportHeader = item.ReprotHeader;
    }

</div>