Fleet/Controllers/ExceptionsController.cs
using CipherLib;
using Fleet.Classes;
using Fleet.Filters;
using Fleet.ViewModels;
using FleetDataService;
using FleetDataService.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Serialization;
using WebMatrix.WebData;
using Fleet.Models;
using CYGNUS.Classes;
using FleetDataService.ViewModels;
using CYGNUS.Models;
using System.Net.Mail;

namespace Fleet.Controllers
{
    [Authorize]
    [NoDirectAccess]
    public class ExceptionsController : BaseController
    {
        FleetDataService.ExceptionsService ES = new FleetDataService.ExceptionsService();
        FleetDataService.MasterService MS = new FleetDataService.MasterService();
        FleetDataService.FleetService FS = new FleetDataService.FleetService();

        GeneralFuncations GF = new GeneralFuncations();
        string ControllerName = "ExceptionsController";

        #region MF Cancellation

        public ActionResult MFCancellation()
        {
            MFCancellationViewModel MFCVM = new MFCancellationViewModel();
            return View(MFCVM);
        }

        public JsonResult GetMFCalDetail(string tcno)
        {
            List<SelectListItem> list = new List<SelectListItem> { };
            try
            {
                DataTable Dt = ES.Get_Data_From_MFNo(tcno);
                List<webx_THC_SUMMARY> MFList = DataRowToObject.CreateListFromTable<webx_THC_SUMMARY>(Dt);
                string manual_tcno = "";
                string TCDT = "";
                string tcbr = "";
                bool flag = false;
                if (MFList.Count > 0)
                {
                    flag = true;
                    manual_tcno = Dt.Rows[0]["manual_tcno"].ToString();
                    TCDT = Dt.Rows[0]["TCDT"].ToString();
                    tcbr = Dt.Rows[0]["tcbr"].ToString();
                }

                return new JsonResult()
                {
                    Data = new
                    {
                        manual_tcno = manual_tcno,
                        TCDT = TCDT,
                        tcbr = tcbr,
                        flag = flag
                    }
                };
                //return Json(new
                //{
                //    Data = new
                //    {
                //        manual_tcno = manual_tcno,
                //        TCDT = TCDT,
                //        tcbr = tcbr,
                //        flag = flag
                //    }
                //}, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Error_Logs(ControllerName, "GetMFCalDetail", "Json", "Listing", ex.Message);
                return Json(list);
            }
        }

        [HttpPost]
        public ActionResult MFCancellation(MFCancellationViewModel MFCVM)
        {
            DataTable DT = ES.usp_Manifest_Do_Cancel(MFCVM.MFCnlModel.tcno, BaseUserName);

            return RedirectToAction("MF_CancellationDone", new { tcno = MFCVM.MFCnlModel.tcno });
        }

        public ActionResult MF_CancellationDone(string TCNO)
        {
            ViewBag.TCNO = TCNO;
            return View();
        }

        #endregion

        #region THC Cancellation

        public ActionResult THCCancellation()
        {
            MFCancellationViewModel THVVM = new MFCancellationViewModel();
            THVVM.THCCnlList = new List<vw_MFCancellation>();
            ViewBag.Flag = "THCCancellationlist";
            return View(THVVM);
        }

        [HttpPost]
        public ActionResult THCCancellationlist(MFCancellationViewModel VM)
        {
            List<vw_MFCancellation> ListTHCln = new List<vw_MFCancellation>();
            DataTable DT = ES.ListOFTHCCancellation(BaseLocationCode, GF.FormateDate(VM.MFCnlModel.FromDate), GF.FormateDate(VM.MFCnlModel.ToDate), VM.MFCnlModel.thcnoumber);
            ListTHCln = DataRowToObject.CreateListFromTable<vw_MFCancellation>(DT);
            VM.THCCnlList = ListTHCln;
            if (VM.THCCnlList.Count > 0)
            {
                ViewBag.Flag = "THCCancellationSubmit";
            }
            else
            {
                ViewBag.Flag = "THCCancellation";
            }
            return View("THCCancellation", VM);
        }

        public ActionResult THCCancellationSubmit(MFCancellationViewModel VM, List<vw_MFCancellation> THCclnList)
        {
            string xmlTHC = "<root>";
            string TCNO = "";
            DataTable DT = new DataTable();
            try
            {
                foreach (var item in THCclnList.Where(c => c.IsChecked == true).ToList())
                {
                    xmlTHC = xmlTHC + "<THC>" + "<THCNO>" + item.THCNO + "</THCNO>" + "</THC>";
                    TCNO = item.THCNO + ',' + TCNO;
                }
                xmlTHC = xmlTHC + "</root>";
                DT = ES.usp_XML_THC_Cancellation(xmlTHC, BaseUserName);
            }
            catch (Exception Ex)
            {
                ViewBag.StrError = "Error : " + Ex.Message;
                return View("Error");
            }

            return RedirectToAction("THCCancellationDone", new { TCNO = TCNO });
        }
        public ActionResult THCCancellationDone(string TCNO)
        {
            ViewBag.TCNO = TCNO;
            return View();
        }

        #endregion

        #region PRS/DRS Cancellation

        public ActionResult PDCCancellationCriteria()
        {
            MFCancellationViewModel THVVM = new MFCancellationViewModel();
            THVVM.PDCCnlList = new List<vw_PDCCancellation>();
            ViewBag.Flag = "PDCCancellationList";
            return View(THVVM);
        }

        [HttpPost]
        public ActionResult PDCCancellationList(MFCancellationViewModel VM)
        {
            List<vw_PDCCancellation> ListPDCCln = new List<vw_PDCCancellation>();
            DataTable DT = ES.ListOFPDCCancellation(BaseLocationCode, VM.MFCnlModel.FilterType, GF.FormateDate(VM.MFCnlModel.FromDate), GF.FormateDate(VM.MFCnlModel.ToDate), VM.MFCnlModel.thcnoumber);
            ListPDCCln = DataRowToObject.CreateListFromTable<vw_PDCCancellation>(DT);
            VM.PDCCnlList = ListPDCCln;
            if (ListPDCCln.Count > 0)
            {
                ViewBag.Flag = "PDCCancellationSubmit";
            }
            else
            {
                ViewBag.Flag = "PDCCancellationList";
            }
            return View("PDCCancellationCriteria", VM);
        }

        public ActionResult PDCCancellationSubmit(MFCancellationViewModel VM, List<vw_PDCCancellation> PDCclnList)
        {
            try
            {
                string xmlPDC = "<root>";
                string PDCNO = "";
                foreach (var item in PDCclnList.Where(c => c.IsChecked == true).ToList())
                {
                    xmlPDC = xmlPDC + "<PDC>" + "<PDCNO>" + item.pdcno + "</PDCNO>" + "</PDC>";
                    if (PDCNO == "")
                    {
                        PDCNO = item.pdcno;
                    }
                    else
                    {
                        PDCNO = item.pdcno + ',' + PDCNO;
                    }

                }
                xmlPDC = xmlPDC + "</root>";
                DataTable DT = ES.usp_XML_PDC_Cancellation(xmlPDC, BaseUserName, VM.MFCnlModel.FilterType);
                return RedirectToAction("PDCCancellationDone", new { PDCNO = PDCNO });
            }
            catch (Exception ex)
            {
                ViewBag.StrError = ex.Message.ToString().Replace('\n', ' ');
                return View("Error");
            }
        }

        public ActionResult PDCCancellationDone(string PDCNO)
        {
            ViewBag.PDCNO = PDCNO;
            return View();
        }

        #endregion

        #region Loding Sheet Cancellation

        public ActionResult LodingSheetCnl()
        {
            MFCancellationViewModel MFCVM = new MFCancellationViewModel();
            return View(MFCVM);
        }

        [HttpPost]
        public ActionResult LodingSheetCnl(MFCancellationViewModel VM)
        {
            string commandText = "Select TCBR,FINAL_TC from webx_TCHDR_tmp where TCNO='" + VM.MFCnlModel.LS + "'";
            DataTable Dt = GF.getdatetablefromQuery(commandText);
            VM.MFCnlModel.tcbr = Dt.Rows[0]["TCBR"].ToString();
            VM.MFCnlModel.FINAL_TC = Dt.Rows[0]["FINAL_TC"].ToString();
            VM.MFCnlModel.THCBR = BaseLocationCode;
            if (VM.MFCnlModel.tcbr != VM.MFCnlModel.THCBR)
            {
                ViewBag.Message = "Loading Sheet doesn't belongs to this location ,therefore cann't delete !!!";
            }
            else if (VM.MFCnlModel.FINAL_TC == "Y")
            {
                ViewBag.Message = "This Loading Sheet No.: " + VM.MFCnlModel.LS + " is already converted to manifest ,therefore cann't delete !!!";
            }
            else
            {
                string sql_delete = "Update webx_trans_docket_status set LS=NULL where LS='" + VM.MFCnlModel.LS + "'";
                DataTable Dt1 = GF.getdatetablefromQuery(sql_delete);
                ViewBag.Message = "Loading Sheet No. : " + VM.MFCnlModel.LS + " has been deleted successfully .";
            }
            return View("LodingSheetCnlDone", VM);
        }


        #endregion

        #region Thc Financial Tracker

        public ActionResult ThcFinancialTrackerCriteria()
        {
            ThcFinancialTrackerCriteria TFTCM = new ThcFinancialTrackerCriteria();
            return View(TFTCM);
        }

        public JsonResult CheckValidDOCNO(string DocType, string DocNo, string NumberType)
        {
            string strResult = ES.CheckValidDOCNO(DocType, DocNo, NumberType);
            if (strResult == "0")
            {

Fleet/Views/Exceptions/CnoteFieldsEditCriteria.cshtml
@model Fleet.ViewModels.Docket
@{
    ViewBag.Title = "Docket Financial Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("CnoteFieldsEditCriteriaAdd", "Exceptions", FormMethod.Post, new { id = "form_sample", @class = "form-horizontal", enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-md-10">
            <div class="portlet box @ViewBag.TableBoxColor ">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-filter"></i>@ViewBag.Title Criteria
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="form-body">
                        <div class="alert alert-danger display-hide">
                            <button class="close" data-close="alert"></button>
                            You have some form errors. Please check below.
                        </div>
                        <div class="alert alert-success display-hide">
                            <button class="close" data-close="alert"></button>
                            Your form validation is successful!
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="form-group">
                                        <label class="control-label col-md-4">
                                            @ViewBag.DKTCalledAs No.
                                        </label>
                                        <div class="col-md-6">
                                            @Html.TextBoxFor(c => c.DockNo, new { placeholder = "Enter " + @ViewBag.DKTCalledAs + " No. ", @class = "span6 m-wrap required2 form-control", autocomplete = "off" })
                                            @Html.Hidden("DKTError")
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions fluid">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-8">
                                <button type="button" id="btnSubmit" disabled="disabled" class="btn btn-sm blue"><i class="fa fa-search"></i>&nbsp;Search</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    var FormComponents = function (DomainName) {

        var Formvalidate = function (DomainName) {

            var form1 = $('#form_sample');
            var error1 = $('.alert-danger', form1);
            var success1 = $('.alert-success', form1);

            $.validator.addMethod('checkDKTEditAvailability', function (value) {
                App.blockUI({ boxed: true });
                var StrURL = DomainName + "/Operation/CheckEditDocket?DocketNo=" + $("#DockNo").val().trim();
                // alert("hello " + StrURL);
                var result1 = $.ajax({
                    async: false,
                    type: 'POST',
                    contentType: 'application/json; charset=utf-8',
                    url: StrURL,
                    dataType: 'json',
                    data: {},
                });

                var d1 = JSON.parse(result1.responseText);

                $("#DKTError").val(d1.Status);

                if (d1.Status == "Done") {
                    $("#btnSubmit").attr("disabled", false);
                    App.unblockUI();
                    return true;
                }
                else {
                    $("#btnSubmit").attr("disabled", true);
                    App.unblockUI();
                    return false;
                }

            }, "");

            form1.validate({
                doNotHideMessage: true,
                errorElement: 'span', //default input error message container
                errorClass: 'help-block', // default input error message class
                // errorClass: 'validate-inline',
                focusInvalid: false, // do not focus the last invalid input


                rules: {
                    'DockNo': {
                        checkDKTEditAvailability: true,
                    },
                },
                messages: {
                    'DockNo': {
                        checkDKTEditAvailability: function () {
                            return $("#DKTError").val()
                        }
                    },
                    //'ServiceFor': {
                    //    required: "Please select at least one service for option",
                    //    minlength: jQuery.format("Please Select at Least One Service For Option")
                    //}
                },
                errorPlacement: function (error, element) { // render error placement for each input type
                    //if (element.parents('.checkbox-list').size() > 0) {
                    //    error.appendTo(element.parents('.checkbox-list').attr("data-error-container"));
                    //} else {
                    error.insertAfter(element); // for other inputs, just perform default behavior
                    //}
                },
                invalidHandler: function (event, validator) { //display error alert on form submit
                    success1.hide();
                    error1.show();
                    App.scrollTo(error1, -200);
                },
                highlight: function (element) { // hightlight error inputs
                    $(element)
                        .closest('.form-group').addClass('has-error'); // set error class to the control group
                },
                unhighlight: function (element) { // revert the change done by hightlight
                    $(element)
                        .closest('.form-group').removeClass('has-error'); // set error class to the control group
                },
                success: function (label) {
                    label
                        .closest('.form-group').removeClass('has-error'); // set success class to the control group
                },
                submitHandler: function (form) {
                    success1.show();
                    error1.hide();
                    //form1.submit();
                }
            });
        }
        return {
            //main function to initiate the module
            init: function (DomainName) {
                Formvalidate(DomainName);

                $('#btnSubmit').click(function () {

                    var form = $('#form_sample');
                    if (form.valid() == false) {
                        return false;
                    }
                    App.blockUI({ boxed: true });
                    document.forms["form_sample"].submit();
                });
            }
        };
    }();

</script>

Fleet/Views/Exceptions/Customergeneratemail.cshtml
@model Fleet.ViewModels.CustomergeneratemailviewModel
@{
    ViewBag.Title = " Customer Generate Mail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("CustomergeneratemailList", "Exceptions", FormMethod.Post, new { id = "form_sample", @class = "form-horizontal", enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box @ViewBag.TableBoxColor">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-edit"></i>@ViewBag.Title
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="form-body">
                        <div class="form-group">
                            <div class="">
                                <div class="col-md-4">
                                    <label class="control-label col-md-4">Docket No.</label>
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(c => c.CnoteNo, new { placeholder = "Docket No", @class = "form-control required required2" })
                                        @Html.Hidden("DKTError")
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <button type="submit" id="btnSubmit" class="btn btn-sm green controls"><i class="fa fa-check"></i>&nbsp;Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">

    var FormComponents = function (DomainName) {

        var Formvalidate = function (DomainName) {
            var form1 = $('#form_sample');
            var error1 = $('.alert-danger', form1);
            var success1 = $('.alert-success', form1);

            $.validator.addMethod('checkDKTSTAXEditAvailability', function (value) {
                App.blockUI({ boxed: true });
                var StrURL = DomainName + "/Exceptions/Check_DocketNo_Mail?DocketNo=" + $("#CnoteNo").val().trim();
                // alert("hello " + StrURL);
                var result1 = $.ajax({
                    async: false,
                    type: 'POST',
                    contentType: 'application/json; charset=utf-8',
                    url: StrURL,
                    dataType: 'json',
                    data: {},
                });

                var d1 = JSON.parse(result1.responseText);

                $("#DKTError").val(d1.Status);

                if (d1.Status == "Done") {
                    $("#btnSubmit").attr("disabled", false);
                    App.unblockUI();
                    return true;
                }
                else {
                    $("#btnSubmit").attr("disabled", true);
                    App.unblockUI();
                    return false;
                }

            }, "");

            form1.validate({
                doNotHideMessage: true,
                errorElement: 'span', //default input error message container
                errorClass: 'help-block', // default input error message class
                // errorClass: 'validate-inline',
                focusInvalid: false, // do not focus the last invalid input
                //ignore: "",

                rules: {
                    'CnoteNo': {
                        checkDKTSTAXEditAvailability: true,
                    },
                },
                messages: {
                    'CnoteNo': {
                        checkDKTSTAXEditAvailability: function () {
                            return $("#DKTError").val()
                        }
                    },
                },
                invalidHandler: function (event, validator) { //display error alert on form submit
                    success1.hide();
                    error1.show();
                    App.scrollTo(error1, -200);
                },

                highlight: function (element) { // hightlight error inputs
                    $(element)
                        .closest('.form-group').addClass('has-error'); // set error class to the control group
                },

                unhighlight: function (element) { // revert the change done by hightlight
                    $(element)
                        .closest('.form-group').removeClass('has-error'); // set error class to the control group
                },

                success: function (label) {
                    label
                        .closest('.form-group').removeClass('has-error'); // set success class to the control group
                },

                submitHandler: function (form) {
                    success1.show();
                    error1.hide();

                    App.blockUI({ boxed: true });
                    document.form["form_sample"].submit();

                }

            });
        }

        var DocketNoChange = function (DomainName) {

            $("#CnoteNo").focusout(function () {

                App.blockUI({ boxed: true });

                var DocketNo = $(this).val();
                var DocketNoId = $(this).attr("id");
                var Id = $(this).attr("id");

                var StrURL1 = DomainName + '/Exceptions/Check_DocketNo_Mail?DocketNo=' + DocketNo;
                $.ajax({
                    url: StrURL1,
                    cache: false,
                    data: {},
                    type: 'POST',
                    success: function (data) {
                        if (data.IsRecordFound == "1") {

                            if (data.flag == "Y") {

                            }
                            else {
                                alert(data.exmessage)
                            }
                            App.unblockUI();
                        }
                    },
                    error: function (req, status, error) {
                        alert("error " + req + "   " + status + "   " + error);
                        App.unblockUI();

                    }
                });

            });
        }

        var Events = function (DomainName) {

            $("#btnSubmit").attr("disabled", true);

        }

        return {
            //main function to initiate the module
            init: function (DomainName) {

                Formvalidate(DomainName);
                Events(DomainName);
            }
        }
    }();
</script>

Fleet/Views/Exceptions/DocketBookingExceptionList.cshtml
@model Fleet.ViewModels.DoketBookingExceptionViewModel
@using FleetDataService.Models;
@using Fleet.Classes;
@{
    ViewBag.Title = "Docket Booking Exception";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("DoketBookingExceptionSubmit", "Exceptions", FormMethod.Post, new { @id = "submit_form", @class = "form-horizontal" }))
{
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box @ViewBag.TableBoxColor">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-list"></i>@ViewBag.Title List
                    </div>
                </div>
                <div class="portlet-body">


                    <div class="row">
                        <div class="col-md-4 form-group">
                            <label class="control-label col-md-4">Docket No</label>
                            <div class="col-md-8">
                                @Html.TextBoxFor(c => c.Dkt.DOCKNO, new { placeholder = "Docket No", @class = "m-wrap form-control", @readonly = true })
                            </div>
                        </div>
                        <div class="col-md-4 form-group">
                            <label class="control-label col-md-4">Docket Date</label>
                            <div class="col-md-8">
                                @Html.TextBoxFor(c => c.Dkt.DOCKDT, Convert.ToDateTime(Model.Dkt.DOCKDT).ToString("dd MMM yyyy"), new { placeholder = "Docket Date", @class = "m-wrap form-control", @readonly = true })
                            </div>
                        </div>
                        <div class="col-md-4 form-group">
                            <label class="control-label col-md-4">Pay Base</label>
                            <div class="col-md-8">
                                @Html.TextBoxFor(c => c.Dkt.PAYBAS, new { placeholder = "Pay Base", @class = "m-wrap form-control", @readonly = true })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 form-group">
                            <label class="control-label col-md-4">Party Code</label>
                            <div class="col-md-8">
                                @Html.TextBoxFor(c => c.Dkt.CSGENM, new { placeholder = "Party Code", @class = "m-wrap form-control ", @readonly = true })
                            </div>
                        </div>
                        <div class="col-md-4 form-group">
                            <label class="control-label col-md-4">EDD Date</label>
                            <div class="col-md-8">
                                @Html.TextBoxFor(c => c.Dkt.CDELDT, Convert.ToDateTime(Model.Dkt.CDELDT).ToString("dd MMM yyyy"), new { placeholder = "EDD Date", @class = "m-wrap form-control", @readonly = true })
                            </div>
                        </div>

                        <div class="col-md-4 form-group">
                            <label class="control-label col-md-4">Schedule Date</label>
                            <div class="col-md-8">
                                <div class="input-group input-medium date date-picker" data-date-format="dd MMM yyyy" data-date-start-date="">
                                    @Html.TextBox("Dkt.SDD_Date", String.Format("{0:dd MMM yyyy }", Convert.ToDateTime(Model.Dkt.SDD_Date).ToString("dd MMM yyyy")), new { @class = "form-control required required2", @readonly = "True", @min = "0" })
                                    <span class="input-group-btn">
                                        <button class="btn default date-set" type="button"><i class="fa fa-calendar"></i></button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-body">
                        <div class="form-actions fluid">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-9">
                                    <a href="@Url.Content("~/Exceptions/DoketBookingException")" class="btn btn-sm default controls"><i class="fa fa-arrow-left"></i>&nbsp;Back to criteria</a>
                                    <button type="submit" id="btnSubmit" class="btn btn-sm green"><i class="fa fa-check"></i>&nbsp;Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
}

<script type="text/javascript">

    var FormComponents = function (DomainName) {

        var Formvalidate = function (DomainName) {
            var form1 = $('#submit_form');
            var error1 = $('.alert-danger', form1);
            var success1 = $('.alert-success', form1);

            form1.validate({
                doNotHideMessage: true,
                errorElement: 'span', //default input error message container
                errorClass: 'help-block', // default input error message class
                // errorClass: 'validate-inline',
                focusInvalid: false, // do not focus the last invalid input
                ignore: "",

                rules: {
                    //account dateFuture
                },

                messages: {

                },

                invalidHandler: function (event, validator) { //display error alert on form submit
                    success1.hide();
                    error1.show();
                    App.scrollTo(error1, -200);
                },

                highlight: function (element) { // hightlight error inputs
                    $(element)
                        .closest('.form-group').addClass('has-error'); // set error class to the control group
                },

                unhighlight: function (element) { // revert the change done by hightlight
                    $(element)
                        .closest('.form-group').removeClass('has-error'); // set error class to the control group
                },

                success: function (label) {
                    label
                        .closest('.form-group').removeClass('has-error'); // set success class to the control group
                },


            });
        }

        return {
            //main function to initiate the module
            init: function (DomainName) {

                Formvalidate(DomainName);

                $("#btnSubmit").click(function () {

                    App.blockUI({ boxed: true });
                    $("#submit_form").submit();
                });

                $(".date-picker").datepicker({

                    rtl: App.isRTL(),
                    format: "dd MM yyyy",
                    showMeridian: true,
                    autoclose: true,
                    pickerPosition: (App.isRTL() ? "bottom-right" : "bottom-left"),
                    startDate: new Date($("#Dkt_CDELDT").val()),
                    //endDate: new Date($("#Dockno_0100029__CDELDT").val()),
                    todayBtn: true
                })

                if (("@Model.Dkt.SDD_Date.ToString("dd MMM yyyy")" == "01 Jan 0001") || ("@Model.Dkt.SDD_Date.ToString("dd MMM yyyy")" == "01 Jan 1990")) {
                    $("#Dkt_SDD_Date").val("");
                }
            }
        };
    }();

</script>